######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 3 21:20:00 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . ui
INCLUDEPATH += .

# Input
HEADERS += main_window.h
FORMS += ui/main.ui
SOURCES += main.cpp main_window.cpp
