######################################################################
# Automatically generated by qmake (2.01a) ?? ???? 10 23:05:19 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . ui
INCLUDEPATH += .

# Input
HEADERS += main_window.h pomodoro.h
FORMS += ui/main.ui
SOURCES += main.cpp main_window.cpp pomodoro.cpp
